### ISSUE TITLE
Only RSP1A?

### ISSUE THREAD

**Issue by BikerJohn66** [rpatel3001/docker-soapy2tcp-channels#3]
Would it be possible to add support for the other SDRPlay models? They all use the same driver. I tried to run it with a RSPdx but everytime I tried it I got an error message that no device was found.
![image](https://github.com/rpatel3001/docker-soapy2tcp-channels/assets/153925980/ab00f90b-3b4a-4b46-b324-e55965acb940)

**Comment by rpatel3001** [comment]
As far as I know there shouldn't be anything causing an RSPdx not to work.

Some quick troubleshooting questions:

1. Can you use the device on the host machine?
2. Is the device properly passed into the Docker container?
3. Is the device already in use by some other software?
4. Have you tried the soapyMiri driver or the sdrplay api v3 release?

**Comment by BikerJohn66** [comment]
The system is a Raspberry Pi5 that has the Bookworm OS and it is up-to-date. If I swap the RSPdx for a RSP1A, the software finds the RSP1A and runs. The RSPdx was used on that Pi earlier for dumphfdl also via soapy. The docker-compose.yml has the SOAPY=driver=sdrplay,serial= with the serial number of the RSPdx. Change it to the serial of the RSP1A was all that was needed to use it but with the RSPdx and it's serial number it doesn't work.
On the Pi5 nothing else runs that uses the soapy system so the RSPdx is not in use by any other software.
The sdrplay 3.14 api is installed on the pi when it was installed, the soapyMiri driver I didn't try.

**Comment by rpatel3001** [comment]
If you run SoapySDRUtil - -probe or - -find on the host, does it find the rspdx? The latest version of the container uses sdrplay api v2 because v3 doesn't play nice with multiple containers. Try disabling the api service on the host, and if that alone doesn't work, try using the api v3 version, the tag to pin to is on the releases page of the repo.

**Comment by BikerJohn66** [comment]
The RSPdx is found with SoapySDRUtil, both with the --probe="driver=sdrplay" and with the --find option.
Via the 'sudo systemctl stop sdrplay' command I disabled the installed (V3) API but the result is the same.
I pulled the API V3 Linux/ARM but that also has the same result, either with the API that's installed on the RPi switched on or off.

**Comment by rpatel3001** [comment]
Can you post the result of `lsusb` and `ls - l /dev/bus/usb/*` and your compose file?

**Comment by BikerJohn66** [comment]
In the yml file I commented out most parts as I wanted to take a step by step approach.

john@Pi5a:~ $ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1df7:3030 SDRplay RSPdx
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

john@Pi5a:~ $ ls -l /dev/bus/usb/*
/dev/bus/usb/001:
total 0
crw-rw-r-- 1 root root 189, 0 Mar 15 15:07 001
crw-rw-rw- 1 root root 189, 1 Mar 15 15:07 002

/dev/bus/usb/002:
total 0
crw-rw-r-- 1 root root 189, 128 Mar 15 15:07 001

/dev/bus/usb/003:
total 0
crw-rw-r-- 1 root root 189, 256 Mar 15 15:07 001

/dev/bus/usb/004:
total 0
crw-rw-r-- 1 root root 189, 384 Mar 15 15:07 001

john@Pi5a:/opt/adsb $ cat docker-compose.yml
```
version: '3.8'

services:
  soapy2chans:
    container_name: soapy2chans
    hostname: soapy2chans
    image: ghcr.io/rpatel3001/docker-soapy2tcp-channels
    restart: always
#    device_cgroup_rules:
#      - 'c 189:* rwm'
    devices:
      - /dev/bus/usb
    environment:
      - TZ=${FEEDER_TZ}
      - SOAPY=driver=sdrplay,serial=223405D447
      - RATE=8400000
      - FREQ=133500000
      - GAIN=agc=true
      - BASEPORT=1234
      - CHANS=131000000,4;136600000,4;133500000,1
      - EXIT_ON_ERROR=true
    volumes:
      - /dev:/dev:ro

  acarsmuxer:
    container_name: acarsmuxer
    hostname: acarsmuxer
    image: ghcr.io/rpatel3001/docker-rtlmuxer
    restart: always
    depends_on:
      - soapy2chans
    ports:
      - 7374:7374
    environment:
      - TZ=${FEEDER_TZ}
      - SRC_ADDR=soapy2chans
      - SRC_PORT=1234

  vdlm2muxer:
    container_name: vdlm2muxer
    hostname: vdlm2muxer
    image: ghcr.io/rpatel3001/docker-rtlmuxer
    restart: always
    depends_on:
      - soapy2chans
    ports:
      - 7375:7374
    environment:
      - TZ=${FEEDER_TZ}
      - SRC_ADDR=soapy2chans
      - SRC_PORT=1235

#  airbandmuxer:
#    container_name: airbandmuxer
#    hostname: airbandmuxer
#    image: ghcr.io/rpatel3001/docker-rtlmuxer
#    restart: always
#    depends_on:
#      - soapy2chans
#    ports:
#      - 7376:7374
#    environment:
#      - TZ=${FEEDER_TZ}
#      - SRC_ADDR=soapy2chans
#      - SRC_PORT=1236

  dumpvdl2:
    container_name: dumpvdl2
    hostname: dumpvdl2
    image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2
    restart: always
    depends_on:
      - vdlm2muxer
    environment:
      - TZ=${FEEDER_TZ}
      - SOAPYSDR=driver=rtltcp,rtltcp=vdlm2muxer:7374
      - CENTER_FREQ=136600000
      - FREQUENCIES=136725000;136775000;136800000;136825000;136875000;136975000
      - FEED_ID=JK_EHEH
      - VDLM_FILTER_ENABLE=true
#      - ZMQ_MODE=server
#      - ZMQ_ENDPOINT=tcp://0.0.0.0:45555
    tmpfs:
      - /run:exec,size=64M
      - /var/log
#
#  acarsdec:
#    container_name: acarsdec
#    hostname: acarsdec
#    image: ghcr.io/sdr-enthusiasts/docker-acarsdec:latest
#    restart: always
#    depends_on:
#      - acarsmuxer
#    environment:
#      - TZ=${FEEDER_TZ}
#      - SOAPYSDR=driver=rtltcp,rtltcp=acarsmuxer:7374
##      - FREQUENCIES=130.825;130.850;131.525;131.550;131.725;131.850;131.825;131.475
##      - FREQUENCIES=129.950;130.025;130.425
#      - FREQUENCIES=130.825;130.850;131.525;131.550;131.725;131.850;131.825;131.475
#      - RTLMULT=168
#      - FEED_ID=RG_EGHQA
#      - CENTER_FREQ=131000000
#      - OUTPUT_SERVER=acars_router
#      - OUTPUT_SERVER_PORT=5550
#      - QUIET_LOGS=false
#    tmpfs:
#      - /run:exec,size=64M
#      - /var/log,size=64M
#
#  acars_router:
#    image: ghcr.io/sdr-enthusiasts/acars_router:test
#    labels:
#      - "autoheal=true"
#    tty: true
#    ports:
#      - 55556:15556
#      - 55555:15555
#      - 55550:15550
#    container_name: acars_router
#    restart: always
#    environment:
#      - TZ=${FEEDER_TZ}
#      - AR_SEND_UDP_HFDL=acarshub:5556;192.168.2.7:5556
#      - AR_SEND_TCP_HFDL=feed.airframes.io:5556
#
#      # The line below should be uncommented if you are receiving acars data from acarsdec AND want to feed airframes
#      #- AR_SEND_UDP_ACARS=acarshub:5550;feed.airframes.io:5550;feed.adsb.one:5550;192.168.1.3:5550
#      # The line below should uncommented if you are receiving VDLM, using dumpvdl2 AND want to feed airframes
#      #- AR_SEND_UDP_VDLM2=acarshub:5555;feed.airframes.io:5552;feed.adsb.one:5555;192.168.1.3:5555
#      # The line below should uncommented if you are receiving dumpvdl2 AND using ZMQ (recommended)
#      #- AR_RECV_ZMQ_VDLM2=dumpvdl2:45555
#      #- AR_RECV_ZMQ_HFDL=192.168.1.41:20556;192.168.1.42:20557;192.168.1.43:20558;192.168.1.78:20559;192.168.1.42:20560
#    tmpfs:
#      - /run:exec,size=64M
#      - /var/log
#
#
#  acarshub:
#    image: ghcr.io/sdr-enthusiasts/docker-acarshub:latest
#    tty: true
#    container_name: acarshub
#    restart: always
#    devices:
#      - /dev/bus/usb:/dev/bus/usb
#    ports:
#      - 81:80
#      - 5550:5550/udp
#      - 5555:5555/udp
#      - 15550:15550
#      - 15555:15555
#    volumes:
#      - /opt/adsb/acarsdata:/run/acars
#    tmpfs:
#      - /database:exec,size=64M
#      - /run:exec,size=64M
#      - /var/log,size=64M
#    environment:
#      - TZ=${FEEDER_TZ}
#      - ENABLE_HFDL=EXTERNAL
#      - ENABLE_VDLM=external
#      - ENABLE_ACARS=external
#      - FEED=true
#      - MIN_LOG_LEVEL=3
#      - TAR1090_URL=http://192.168.2.7/tar1090
#  #      - IATA_OVERRIDE=UP|UPS|United Parcel Service;GS|FTH|Mountain Aviation (Foothills);GS|EJA|ExecJet
#      - ENABLE_ADSB=true
#      - ADSB_LAT=${FEEDER_LAT}
#      - ADSB_LON=${FEEDER_LONG}
#      - ADSB_URL=http://192.168.2.7/tar1090/data/aircraft.json

```
